### ISSUE TITLE
Upgrade Python scripts to be compatible with versions 2.6, 2.7 and 3.x

### ISSUE THREAD

**Issue by wfspotz** [TriBITSPub/TriBITS#119]
**Description:**

I am willing to take a crack at upgrading the TriBITS Python scripts to run under 3.0, while maintaining compatibility with 2.6. I'll need some TriBITS guidance at the beginning, though.

**Tasks:**

1. Update the Python code to work with Python 2 and 3 [Done]
1. Resolve a few remaining issues (see [below](https://github.com/TriBITSPub/TriBITS/issues/119#issuecomment-235696676)):
  1. Strengthen tests involving printed dicts back to original strength ... Fixed, see [below]() and commit 7ad9c4e [Done]
  1. Address short char encoding functions [Done - if documenting the functions is sufficient]
  1. Eliminate duplication [Done]
1. Test out for CASL VERA, and especially the CDash query code actually calling CDash [Done]
1. Final review by Ross [Done]
1. Push to TriBITS github/master [Done]
1. Sync to Trilinos/cmake/tribit/ for Trilinos GitHub develop branch [Done]
1. Delete the python3 branch [Done]
1. Final signoff by @wfspotz  ... IN PROGRESS ...

**Comment by bartlettroscoe** [comment]
> I am willing to take a crack at upgrading the TriBITS Python scripts to run under 3.0, while maintaining compatibility with 2.6.

Excellent!

> I'll need some TriBITS guidance at the beginning, though.

What if I add this info to the TriBITS documentation and then point you to the documentation?  That will help other people who want to contribute to or otherwise modify TriBITS down the line.

**Comment by wfspotz** [comment]
Sounds good.

**Comment by bartlettroscoe** [comment]
@wfspotz,

Sorry for the delay but I have add info on getting started with developing on TriBITS and setting up to run the automated TriBITS test suite in the [README File](https://github.com/TriBITSPub/TriBITS#developing-on-tribits).   Please let me know if anything is not clear.  Once you can run the tests, just change the default version of python in your path to 3.x and then just see what TriBITS tests fail.  You should be able to track down everything by digging into the failing tests.

**Comment by wfspotz** [comment]
@bartlettroscoe,

I am finally getting around to looking at this. I don't have a Fortran compiler installed, so I am building TriBITS with `-D TriBITS_ENABLE_Fortran=OFF`. When I run the tests, 11 of them fail:

```
128:TriBITS_TribitsHelloWorld
129:TriBITS_TribitsHelloWorld_ScaleTimeout
130:TriBITS_TribitsHelloWorld_XSDK_DEFAULTS
131:TriBITS_TribitsExampleProject_ALL_ST_NoFortran
134:TriBITS_TribitsExampleProject_SimpleCxx_DEBUG_int64
135:TriBITS_TribitsExampleProject_CONFIGURE_OPTIONS_FILE
136:TriBITS_TribitsExampleProject_WrapExternal
138:TriBITS_TribitsExampleProject_ALL_WrapExternal_VerboseConfigure
139:TriBITS_TribitsExampleProject_ALL_NoFortran_OverridePackageSourceDir
144:TriBITS_TribitsExampleProject_MixedSharedStaticLibs_shared
145:TriBITS_TribitsExampleProject_MixedSharedStaticLibs_static
```

If I look through the log for `HellowWorld`, I see the following CMake Error:

```
-- The Fortran compiler identification is unknown
CMake Error at /Users/wfspotz/Development/TriBITS/tribits/core/package_arch/TribitsGlobalMacros.cmake:1674 (ENABLE_LANGUAGE):
    No CMAKE_Fortran_COMPILER could be found.
```

Followed by

```
-- Configuring incomplete, errors occurred!
```

So it looks like TriBITS is not handling the absence of a Fortran compiler correctly.

-Bill

**Comment by bartlettroscoe** [comment]
> I am finally getting around to looking at this. I don't have a Fortran compiler installed, so I am building TriBITS with -D TriBITS_ENABLE_Fortran=OFF. When I run the tests, 11 of them fail:

I am taking a look.  I don't think I have tested TriBITS on a machine recently that does not have a compatible Fortran compiler yet.  I will try to dig into what is happening.

**Comment by bartlettroscoe** [comment]
@wfspotz, I think I was able to address this.  Please try to pull the updated 'master' branch for TriBITS (commit 8959441) and give it a try again.

**Comment by wfspotz** [comment]
@bartlettroscoe, with the latest commit, the tests changed from 11 failures to 8:
```
131 - TriBITS_TribitsExampleProject_ALL_ST_NoFortran
134 - TriBITS_TribitsExampleProject_SimpleCxx_DEBUG_int64
135 - TriBITS_TribitsExampleProject_CONFIGURE_OPTIONS_FILE
136 - TriBITS_TribitsExampleProject_WrapExternal
138 - TriBITS_TribitsExampleProject_ALL_WrapExternal_VerboseConfigure
139 - TriBITS_TribitsExampleProject_ALL_NoFortran_OverridePackageSourceDir
144 - TriBITS_TribitsExampleProject_MixedSharedStaticLibs_shared
145 - TriBITS_TribitsExampleProject_MixedSharedStaticLibs_static
```
So your update fixed tests 128, 129, and 130.

The failure for test 131 (`TriBITS_TribitsExampleProject_ALL_ST_NoFortran`) appears to be:
```
TEST_1: Return code = 0
TEST_1: Pass criteria = Match REGEX {Built target simplecxx} [PASSED]
TEST_1: Pass criteria = Match REGEX {‘int SimpleCxx::HelloWorld::someOldFunc.. const’ is deprecated .declared at .*/TribitsExampleProject/packages/simple_cxx/src/SimpleCxx_HelloWorld.hpp:} [FAILED]
TEST_1: Pass criteria = Match REGEX {‘int SimpleCxx::HelloWorld::someOldFunc2.. const’ is deprecated .declared at .*/TribitsExampleProject/packages/simple_cxx/src/SimpleCxx_HelloWorld.hpp:.* .Just don't call this function at all please!} [FAILED]
TEST_1: Pass criteria = Match REGEX {Built target pws_a} [PASSED]
TEST_1: Pass criteria = Match REGEX {Built target pws_b} [PASSED]
TEST_1: Pass criteria = Match REGEX {Built target pws_c} [PASSED]
TEST_1: Result = FAILED
```

**Comment by bartlettroscoe** [comment]
This looks like these tests might be relying on GCC warning messages.  @wfspotz, what compiler are you using?   Is this Clang C++ on a Mac?  What version?

**Comment by wfspotz** [comment]
```
$ grep CMAKE_CXX_COMPILER: CMakeCache.txt 
CMAKE_CXX_COMPILER:FILEPATH=/Applications/Xcode.app/Contents/Developer/usr/bin/g++
$ /Applications/Xcode.app/Contents/Developer/usr/bin/g++ -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```

**Comment by bartlettroscoe** [comment]
@wfspotz, I remembered that I have access to a Mac and I was able to reproduce the failing tests:

```
The following tests FAILED:
	131 - TriBITS_TribitsExampleProject_ALL_ST_NoFortran (Failed)
	134 - TriBITS_TribitsExampleProject_SimpleCxx_DEBUG_int64 (Failed)
	135 - TriBITS_TribitsExampleProject_CONFIGURE_OPTIONS_FILE (Failed)
	136 - TriBITS_TribitsExampleProject_WrapExternal (Failed)
	138 - TriBITS_TribitsExampleProject_ALL_WrapExternal_VerboseConfigure (Failed)
	139 - TriBITS_TribitsExampleProject_ALL_NoFortran_OverridePackageSourceDir (Failed)
	142 - TriBITS_TribitsExampleProject_InsertedPkg (Failed)
	144 - TriBITS_TribitsExampleProject_MixedSharedStaticLibs_shared (Failed)
	145 - TriBITS_TribitsExampleProject_MixedSharedStaticLibs_static (Failed)
```

I will work through these and get them to pass.

**Comment by bartlettroscoe** [comment]
@wfspotz, I think I have all of these failures addressed as of commit 7db2a18.  If you pull from the 'master' branch, you should have all passing tests:

```
100% tests passed, 0 tests failed out of 193

Label Time Summary:
TriBITS    = 166.80 sec (193 tests)
```
Hopefully we can get automated tests set up on OSX at some point in the future to maintain this.

NOTE: These failing tests did not indicate any problems with TriBITS itself on OSX.  The issues were all related to how these tests were specified.

**Comment by wfspotz** [comment]
Great! I pulled and re-ran, and all the tests pass.

I have a desktop MacPro with 12 processors and 2 GPUs, suitable for nightly testing.

**Comment by wfspotz** [comment]
@bartlettroscoe,

I have upgraded the TriBITS python scripts to work under Python 2 and 3, mostly successfully. 192 of the 193 tests pass, under both versions of Python. The one failing test is
```
157 - TriBITS_CheckinTest_UnitTests (Failed)
```
For this test, 189 unit tests pass, 4 fail, with 0 errors. These four unit tests are complicated enough that I am having trouble debugging them. I suspect that I tried to update a `print` statement, introduced an error, and the resulting errors are hidden in a file somewhere. I think you could probably find the errors faster than me.

I have committed my changes to a local branch, `python3`, and I tried to push to the remote repository with
```
$ git push origin python3
ERROR: Permission to TriBITSPub/TriBITS.git denied to wfspotz.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
Let me know how you want to proceed.

**Comment by bartlettroscoe** [comment]
Responding to @wfspotz from [above comment](https://github.com/TriBITSPub/TriBITS/issues/119#issuecomment-234737943):

> Let me know how you want to proceed.

Bill, the best way to more forward is for you to [fork the TriBITS repo into your GitHub account](https://help.github.com/articles/fork-a-repo), push the branch there, and then submit a pull-request as outlined [here](https://github.com/TriBITSPub/TriBITS/wiki/Contributing-to-TriBITS#process_create_pull_request).  If you have never submitted a pull-request (PR) before, please take a look at:

* https://help.github.com/articles/using-pull-requests/

This is the preferred way to do this using GitHub.

After that, you can provide reproduceability instructions for the failing tests (perhaps by giving my an account on your machine?) and then I can see what the issue might be.

**Comment by bartlettroscoe** [comment]
@wfspotz, I would like to experiment with allowing contributors to directly push topic branches to the main TriBITS git repo.  Therefore, I have created a @TriBITSPub/collaborators team (which I added you to if you accept) that should allow you to directly push your branch.  If that works, then we can colloaborate on the same topic branch.  Can you try pushing your local branch directly to the main TriBITS repo and see if that works?

**Comment by wfspotz** [comment]
@bartlettroscoe,

I have pushed the python3 branch to the TriBITS github repository. Reproducing the errors should be easy. I have attached my configuration script for reference (I had to give it a `.txt` suffix for github to recognize it as a text file).

[do-configure.txt](https://github.com/TriBITSPub/TriBITS/files/384321/do-configure.txt)

Note the line
```
    -D PYTHON_EXECUTABLE:FILEPATH=/usr/local/bin/python3 \
```
I use this to switch between Python 2 and 3. You should see the errors for either version of Python.

**Comment by bartlettroscoe** [comment]
I am taking a look right now, first with Python 2.  Any changes I made I will add with new commits that I will push to the shared 'python3' branch.

**Comment by bartlettroscoe** [comment]
@wfspotz, a 1-char change in the commit 8a393db got the remaining tests to pass.  I also commented out the temp `print()` debug statement in commit fbca615.  Now all of the tests pass:

```
$ cd <tribits-build-dir>/
$ make
$ ctest -j12

...

100% tests passed, 0 tests failed out of 203

Label Time Summary:
TriBITS    = 293.50 sec (203 tests)

Total Test time (real) =  26.83 sec
```

and the CheckinTest tests show:

```
----------------------------------------------------------------------
Ran 193 tests in 24.566s

OK
```

I need to look through all of the changes more but it looks like the most common changes where:

* Python 3 requires `print(...)` while Python 2 allowed `print ...`
* Some of the char encodings had to be explicitly changed to 'utf-8' or required other modifications for Python 3 in order for the tests to pass.
* The order of the dictionary keys changes and affects the printed of dict objects (like in error messages) and that breaks the tests.  (I would like to see if there is a platform-independent way to print a dict so that we can keep the strong tests working.  Otherwise, we can grep out parts of the message to look for the elements of the dict or something.)
* Exception are caught with `except Exception as e:` instead of `except Exception, e:`.
* Lines are split with `<string>.splitlines()` instead of `<string.split("\n")`.

I need to do a more detailed review and carefully check all of the same tests are still running as before.   Otherwise, except for a few small issues, this looks good.

The one thing that I would like to see changed are the duplicated very short one-letter functions that are used to handle the char encodings.  It would be nice if these had slightly longer more descriptive names to make the intent a little more clear.  Also, these functions could be reused across most of these files instead of having to create new ones in each *.py file.  The only duplication should be in gitdist.py (which is a 100% standalone script) and GeneralScriptSupport.py.  All other Python code should get these functions from one of those two modules.  @wfspotz. is this something you can look into addressing?

It would also be nice to strengthen the tests that involve printing out dict objects.  The modified tests are very weak and will allow defects to creep in on modification.  It looks like there are a couple of ideas [here](http://stackoverflow.com/questions/20192950/why-items-order-in-a-dictionary-changed-in-python).  Could we build the expected error string by building a dict and then creating the expected string?  That should yield the same printed text, right?

Otherwise, I will do a more detailed review and add a comment to this Issue when I am done.

**Comment by bartlettroscoe** [comment]
> You often used the pattern print "strconst" + strvar + "strconst", which is a little unconventional, but translates very well to this Python 2/3 dual use.

I find that a much more natural way to format strings.  I dislike the C-style formatting of `print "<strconst> %s <strconst>" % (strvar)`.  That does not pass the locality test.  Also, you can format strings like that in C++ and it works well.

> I see two preferable approaches. One would be to compare actual dictionaries if possible. The equals operator does not care about key order. The second approach would be to implement a printing function that sorts the keys and generates a string version of the dictionary based on that key order. I just looked at the pprint module. It sorts dictionary keys before printing, so I think this is the way to go.

The problem with `pprint` is that it prints a dict on multiple lines.  That is not what I want for a more compact error message like this.  I think I thought of a clean portable way to write this test.  I implemented this and tested it with Python 2.7.10 and it passed (see commit 7ad9c4e that I just pushed).  But I don't seem to have access to a machine that has Python 3.x so can you test this on your machine with Python 3.x?

Note that I also fixed this for Python 2.6.6 with the commit f347d36.

> > The one thing that I would like to see changed are the duplicated very short one-letter functions that are used to handle the char encodings.
> 
> I found this solution on the web. The thinking is that Unicode strings are specified in Python 2 with
> 
>     ustr = u'Unicode string'
> 
> and byte arrays are specified in Python 3 with
> 
>     bstr = b'Byte string'
> 
> and so the u(...) and b(...) functions would be reminiscent of this syntax. It is your package, though, so it is your call. We can consolidate the function definitions into a single module, as well. My approach was a first cut and a little hacky.

Okay, I see that idiom documented, for example, here:

  http://stackoverflow.com/questions/6625782/unicode-literals-that-work-in-python-3-and-2

But what about the function 's()' used in CheckinTest_UnitTests.py shown [here](https://github.com/TriBITSPub/TriBITS/blob/python3/test/ci_support/CheckinTest_UnitTests.py#L54)?  Is there an `s'<some-text>'` modifier with Python 3?  I can't find that modifier anywhere.  Does that just mean basic unicode-8 "string".  If is all it is, then that is fine.  We just need to document that to make it clear and why it is needed.

Perhaps we can just add a little documentation for this idiom and then consolidate duplicate implementations of these functions into the two files gitdist.py and GeneralScriptSupport.py?

**Comment by cgbaker** [comment]
I don't run gitdist regularly, but I just noticed the print issue today, on my laptop on which I've apparently updated default python to 3.x. My temporary workaround was to tell my gitdist.py 
`
#!/usr/bin/env python2.7
` 
But obvs that doesn't work in general, so I'm looking forward to the update :)

**Comment by bartlettroscoe** [comment]
> But obvs that doesn't work in general, so I'm looking forward to the update :) 

Good to hear from you Chris!  This is almost ready to go (see the remaining 'tasks' above in the first comment).

@wfspotz, do you think you will be able to refactor and aggregate all of the char encoding functions, document them, and reduce duplication (see [above](https://github.com/TriBITSPub/TriBITS/issues/119#issuecomment-235780458))?  If not, I can likely find some time for that next week to finish this up.

**Comment by wfspotz** [comment]
@bartlettroscoe, @cgbaker,

Yeah, it shouldn't take long. I was required to do a security update that has spiraled out of control, but I should be able to get to it soon.

**Comment by wfspotz** [comment]
@bartlettroscoe, the test fails for Python 3:
```
AssertionError: "Error, the build {'compilation': {'error': 0}, 'buildname': [99 chars]led!" != "Error, the build {'test': {'fail': 0, 'notrun': 0}, 'buildna[99 chars]led!"
- Error, the build {'compilation': {'error': 0}, 'buildname': 'build1', 'update': {'errors': 0}, 'configure': {'error': 5}, 'test': {'fail': 0, 'notrun': 0}} failed!
+ Error, the build {'test': {'fail': 0, 'notrun': 0}, 'buildname': 'build1', 'update': {'errors': 0}, 'configure': {'error': 5}, 'compilation': {'error': 0}} failed!
```
Why the same dictionary hashes two different ways, I have no idea. But this is what I was seeing before.

I added a sorted_str() function to CDashQueryPassFail.py. I use it when the output message is generated, as well as in the test. All tests pass, for both versions of Python. Commit 116a2bda860207f4a96a4ca1c79b697b20ed347e.

I still have the cleanup to do. Will get to it shortly.

**Comment by wfspotz** [comment]
@bartlettroscoe -- I think I am done with the TriBITS conversion. Give it a look.

**Comment by bartlettroscoe** [comment]
@wfspotz , I looked over the changes you made in the last two commits and they look great.  Thanks for doing that!  I wish the Python proper had a `sorted_str()` function for dictionaries.  I think I will rename this `sorted_dict_str()` (because this only works with dict objects, not all types in Python) and move it into GeneralScriptSupport.py so that it can be reused in other functions that need to provide portable strings of dicts.

I also did a manual test of the script `vera_cdash_pass_fail.py` which uses the module CDashQueryPassFail.py and it looks good.  I just wanted to make sure that the real strings returned from the urllib module from this CDash site were still getting converted correctly (and the unit tests can't confirm that because they don't run that actual module).

I will do one last round of testing with Python 2.6.6 and 2.7 and if that all passes, I will rebase and push.

----

**Detailed Notes:**

Testing out with the VERA vera_cdash_pass_fail.py function ...

**A) Passing VERA builds, missing VERADriver build:**

Looking at the VERA CDash site on 2016-07-01:

* https://localhost:55556/testing/index.php?project=VERA&date=2016-07-01

It looks like all of the builds are present and passing.  Running the script:

```
8vt@th232 drivers (master)]$ ./vera_cdash_pass_fail.py --date=2016-07-01
***
*** Check for pass/fail of VERA builds on CDash for 2016-07-01
***

*** Check the VERA project builds ...

Getting data from:

  https://casl-dev.ornl.gov/testing/api/v1/index.php?project=VERA&date=2016-07-01&filtercount=4&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Nightly&field2=subprojects&compare2=92&value2=VUQCore&field3=subprojects&compare3=92&value3=VUQDemos

VERA builds passed!


*** Check the VERADriver project builds ...

Getting data from:

  https://casl-dev.ornl.gov/testing/api/v1/index.php?project=VERADriver&date=2016-07-01&filtercount=1&showfilters=1&field1=groupname&compare1=61&value1=Nightly

VERADriver builds failed!

Error, the expected build 'Linux-TDD-gcc483-pu241' does not exist in the list of builds []

*** Determine overall pass/fail ...
```

Indeed, all of the VERA builds were present and passed and the VERADriver build 'Linux-TDD-gcc483-pu241' does not exist because CDash was configured to clean out builds more than 14 days old.

[Passed]

**B) Missing VERA builds:**

Looking at the VERA CDash site on 2016-07-11:

* https://localhost:55556/testing/index.php?project=VERA&date=2016-07-11

All of the builds are missing (because the test machines were shut down).  Running the script:

```
 ./vera_cdash_pass_fail.py --date=2016-07-11
***
*** Check for pass/fail of VERA builds on CDash for 2016-07-11
***

*** Check the VERA project builds ...

Getting data from:

  https://casl-dev.ornl.gov/testing/api/v1/index.php?project=VERA&date=2016-07-11&filtercount=4&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Nightly&field2=subprojects&compare2=92&value2=VUQCore&field3=subprojects&compare3=92&value3=VUQDemos

VERA builds failed!

Error, the expected build 'Linux-GCC-4.8.3-MPI_RELEASE_DEBUG_SHARED' does not exist in the list of builds []

*** Check the VERADriver project builds ...

Getting data from:

  https://casl-dev.ornl.gov/testing/api/v1/index.php?project=VERADriver&date=2016-07-11&filtercount=1&showfilters=1&field1=groupname&compare1=61&value1=Nightly

VERADriver builds failed!

Error, the expected build 'Linux-TDD-gcc483-pu241' does not exist in the list of builds []

*** Determine overall pass/fail ...

FINAL: One of the VERA or VERADriver builds on 2016-07-11 FAILED
```

That is correct!

[Passed]

**C) VERA and VERADriver builds exist but fail:**

Looking at the VERA CDash site on 2016-07-15:

* https://localhost:55556/testing/index.php?project=VERA&date=2016-07-15

you can see that most of the builds are failing.

Running the script:

```
./vera_cdash_pass_fail.py --date=2016-07-15
***
*** Check for pass/fail of VERA builds on CDash for 2016-07-15
***

*** Check the VERA project builds ...

Getting data from:

  https://casl-dev.ornl.gov/testing/api/v1/index.php?project=VERA&date=2016-07-15&filtercount=4&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Nightly&field2=subprojects&compare2=92&value2=VUQCore&field3=subprojects&compare3=92&value3=VUQDemos

VERA builds failed!

Error, the build {u'buildname': u'Linux-GCC-4.8.3-MPI_DEBUG_DEBUG_SHARED', u'compilation': {u'error': 0, u'time': u'5h 7m 10s', u'timefull': 18430, u'warning': 379}, u'configure': {u'error': 0, u'time': u'11m 24s', u'timefull': 684, u'warning': 48}, u'test': {u'fail': 1, u'notrun': 0, u'pass': 937, u'time': u'1h 57m 45s', u'timefull': 7065}, u'update': {u'errors': 0, u'files': 0, u'time': u'12s', u'timefull': 0.2}} failed!

*** Check the VERADriver project builds ...

Getting data from:

  https://casl-dev.ornl.gov/testing/api/v1/index.php?project=VERADriver&date=2016-07-15&filtercount=1&showfilters=1&field1=groupname&compare1=61&value1=Nightly

VERADriver builds failed!

Error, the build {u'buildname': u'Linux-TDD-gcc483-pu241', u'compilation': {u'error': 0, u'nerrordiffn': 0, u'nerrordiffp': 0, u'nwarningdiffn': 0, u'nwarningdiffp': 0, u'time': u'0s', u'timefull': 0, u'warning': 0}, u'configure': {u'error': 0, u'time': u'1s', u'timefull': 1, u'warning': 0, u'warningdiff': 0}, u'test': {u'fail': 1, u'nfaildiffn': None, u'nfaildiffp': None, u'nnotrundiffn': None, u'nnotrundiffp': None, u'notrun': 0, u'npassdiffn': None, u'npassdiffp': None, u'pass': 11, u'time': u'17h 27m 34s', u'timefull': 62854}, u'update': {u'errors': 0, u'files': 0, u'time': u'0s', u'timefull': 0}} failed!

*** Determine overall pass/fail ...

FINAL: One of the VERA or VERADriver builds on 2016-07-15 FAILED
```

That is also correct!

[Passed]

Unfortunately, we don't have any days in the CDash DB where the VERADriver builds all pass.

**Comment by bartlettroscoe** [comment]
@wfspotz , I completed all of the tasks described below and merged a rebased branch to TriBITS 'master' and snapshotted to Trilinos 'develop' and pushed.

I am putting this into review.  Let me know if you find any problems with this.  Otherwise, we can close.

Thanks again for taking care of this!

----

**Detailed Notes:**

* Rename `sorted_str()` to `sorted_dict_str()` and move it to GeneralScriptSupport.py [Done]

* Test with Python 2.7 [Done]

* Test with Python 2.6.6 [Done]

* Push to TriBITS github/master [Done]

* Sync to Trilinos/cmake/tribits/ and push to Trilinos GitHub develop branch ... There was a merge conflict in the file Trilinos/cmake/tribits/python_utils/download-cmake.py because there were modifications made directly to the Trilinos copy that were not made back in the TriBITS repo.  I resolved these by going with the Trilinos version.  That should not matter since that is not a script that many people use (and I would in fact like to get rid of it and just build CMake from source with install-cmake.py) [Done]

* Push to Trilinos GitHub 'develop' branch [Done]

* Delete local and public python3 branch [Done]

**Comment by wfspotz** [comment]
I will pull from the master branch and test with Python 3, just to be sure. Hopefully later this afternoon.

**Comment by wfspotz** [comment]
@bartlettroscoe,

OK, on the master branch, with Fortran disabled, and in serial/debug mode, 193 of 193 tests pass using Python 3. I have no more issues.

**Comment by bartlettroscoe** [comment]
@wfspotz, thanks for the review!  I will go ahead and close this.

**Comment by bartlettroscoe** [comment]
Looks like this is not complete (see trilinos/Trilinos#541).  The issue is that there may not be any automated test for the tdd_driver.py script.  Actually, the problem is that we don't have automated testing for the `extraEnv` argument for the `echoRunSysCmnd()` function in `GeneralScriptSupport.py`.

I will add a failing unit test and fix this.
